### ISSUE TITLE
Feature Req - Modify Content Metadata

### ISSUE THREAD

**Issue by trainzkid** [LSchallot/JellyRoller#12]
I'd love to be able to use JellyRoller to modify metadata of content in Jellyfin. That way, I can script away mass changes rather than lose sanity mouse-clicking through each individual movie, episode, etc via Jellyfin itself.

Most people seem to use Jellyfin for movies and tv shows they've ripped from dvds or bluray, but I also use mine to store (hoard?) youtube videos downloaded via yt-dlp. Unfortunately, the metadata is often incorrect or missing entirely (even with the help of the youtube metadata plugin thing for Jellyfin!!).

**Comment by LSchallot** [comment]
I can give this a look.  Can you give me an example of something you typically have to do to fix the metadata?

**Comment by trainzkid** [comment]
Apologies for the delay. 

The sections for "Genres", "People", "Studios", and "Tags" all are usually empty and must be manually filled out for me (since these videos are originally YouTube videos and the fields don't match I guess? Tags matches but still doesn't fill in). I usually must also correct the "Release Date" and "Year" fields. 

I figure if I can at least use a script + jellyroller, I don't have to worry about manually editing literally thousands of videos. 

I know this is very much outside the intended purpose of jellyfin, yt-dlp, and maybe even jellyroller, but it's what I've been using them for partially so *shrug*.

**Comment by LSchallot** [comment]
The only way I will consider this out of scope for JellyRoller is if the Jellyfin API doesn't support it.  I will work towards adding it in my spare time.

Do you mind sharing your OS version so I can generate a test build for you?

**Comment by LSchallot** [comment]
Can you give me more details on your typical process of moving videos downloaded via yt-dlp into Jellyfin?  I have a way to upload metadata via API, but it requires the item's id.  If you have this downloaded already, I can parse the ID from the metadata prior to upload.  Otherwise, I worry that I won't be able to save you much effort.

**Comment by LSchallot** [comment]
Bumping target to 0.4.

**Comment by LSchallot** [comment]
Moving target to 0.5 so I can get 0.4 out since there have been some breaking changes with Jellyfin.

**Comment by LSchallot** [comment]
Metadata update command has been added.  It will be included in the 0.5.0 release.
