### ISSUE TITLE
Support for multiple servers

### ISSUE THREAD

**Issue by eepgwde** [LSchallot/JellyRoller#13]
Thanks for developing this system. It's very useful for administering the servers.

I have a number of servers and would like to be able to initiate library scans on each of them from the command-line. At the moment, I have to use sudo with a different user for each of the servers. In that way, each user has a different ~/.config/jellyroller/jellyroller.toml

I think it would be relatively easy to change the naming reference of this file. I'm a Linux user, so I could easily do it with an environment variable before calling jellyroller and then `confy::load(id_conf)` where `id_conf` is ENV['JELLYROLLER_ID'] or "jellyroller" if null.

I don't program in Rust so I can't be much help to you.

**Comment by LSchallot** [comment]
Right now I just rely on the default confy setup for configuration file management.  It is possible to pass a specified configuration file, so I will see about setting up a way to pass multiple configuration files (maybe comma separated) which will hopefully assist with your use case.

**Comment by eepgwde** [comment]
Hello LSchallot. I made it pretty simple for myself in the end. I used this construct
```
( HOME=~srv1 jellyroller server-info )
( HOME=~srv2 jellyroller server-info )
```
And there exists: ~srv1/.config/jellyroller/jellyroller.toml and for ~srv2
