### ISSUE TITLE
Run a series of plugins (execute-task-by-name) in order I specify (enhancement)

### ISSUE THREAD

**Issue by d8f6** [LSchallot/JellyRoller#15]
I am hoping to use this script to automate running plugins from the cli. Currently I can accomplish this with sleep (example: jellyroller execute-task-by-name Update\ Plugins && sleep 5 && jellyroller execute-task-by-name Scan\ Media\ Library). The issue is that the timing will not always be the same. So, basically what I am asking for is a way to know whether or not the previous task is completed, and then run another task afterward.

**Comment by LSchallot** [comment]
Yeah I messed up on the return codes.  Thanks for pointing this out.

Since you mention using a script and having Linux, I will set it up so that a "$?" returns something non-zero.  That should make it straightforward for scripting your tasks.

**Comment by d8f6** [comment]
If a task completes properly the exit code in the shell should be 0. This is correct. What I am asking for may not be possible with the current api? Basically what I want is for the first command not to exit until the task has been completed. It is a timing thing (I think). Let me give an example:


This works because both tasks complete very quickly:
 
`$ jellyroller execute-task-by-name Clean\ Activity\ Log && jellyroller execute-task-by-name Clean\ Log\ Directory`

Task "Clean Activity Log" initiated.
Task "Clean Log Directory" initiated.


This command will fail because the first task takes longer (I am assuming this, I actually don't know why it fails):

`$ jellyroller execute-task-by-name Scan\ Media\ Library && jellyroller execute-task-by-name Clean\ Log\ Directory`

Task "Scan Media Library" initiated. 
Unable to get task id by taskname.

Here is an example of running three commands where both the first and third work, but the second doesn't due to sleeping for 60 seconds between the second and third command:

`jellyroller execute-task-by-name Scan\ Media\ Library && jellyroller execute-task-by-name Scan\ Media\ Library && sleep 60 && jellyroller execute-task-by-name Clean\ Log\ Directory`

Task "Scan Media Library" initiated.
Unable to get task id by taskname.
Task "Clean Log Directory" initiated.


I am not sure if what I am asking for is even possible though. There would need to be a way to parse the output of get-scheduled-tasks and check if all tasks are idle and then running the next command, but running get-scheduled-tasks while a scheduled task is running only outputs "Unable to get scheduled tasks."  (I tested this by running the task from the gui application and then running jellyroller). Hope that makes more sense.

**Comment by LSchallot** [comment]
Fairly certain I have this fixed.  It was in fact a problem with the task details not being handled properly.  I was able to fully replicate your issue and after implementing a small change, everything was fine.  I have some additional items I want to fix before the next release but the main branch will have the fixes implemented if you want to build from source.  Thanks for letting know about the problem.

**Comment by d8f6** [comment]
Awesome, just compiled and it works great now. Thanks for the fix.
