### ISSUE TITLE
Add examples in readme documentation for usage (enhancement)

### ISSUE THREAD

**Issue by d8f6** [LSchallot/JellyRoller#16]
There are two things that were not immediately apparent to me and adding them to the readme would be helpful in my opinion.

1. Upon initial sign-in, url has to include http/https (and port?, not sure as I included port), an example of this would be http://192/168.0.123:8096
I figured it out relatively quickly, but I thought maybe the program didn't work at first.

2. Forward slash is needed to execute tasks with spaces in the name (example: jellyroller execute-task-by-name Scan\ Media\ Library). I tried quotes at first (jellyroller execute-task-by-name "Scan Media Library"), but that did not work. This is on a GNU/Linux host system, I am unsure of how Windows handles this as I do not use that software.

**Comment by LSchallot** [comment]
I will update the documentation with some additional clarification to address both Windows and Linux users.  As far as the port is concerned, that is left up to how the end-user has their instance setup.  For example, I have my primary Jellyfin behind a proxy so I do not need a port in my address; while my test instance requires use of a specified port.

**Comment by d8f6** [comment]
Well maybe some clarity on the proxy vs local instance then? What threw me was actually http://192.168.0.23 vs just 192.168.0.23 though (as opposed to the trailing port number in the ip address). After getting frustrated I just guessed using http:// might work.

**Comment by LSchallot** [comment]
I added some clarification to the README.md that will hopefully make things a little clearer.  Thanks again for the issue.

**Comment by d8f6** [comment]
Thank you for the update.
