### ISSUE TITLE
[FEATURE REQUEST] Modify content images

### ISSUE THREAD

**Issue by nothing2obvi** [LSchallot/JellyRoller#35]
Similar to #12 but I'd love to be able to use JellyRoller to update images for my media. I don't use Jellyfin's option to keep images stored next to media; I want all of my metadata located on the SSD where Jellyfin is installed, not on an HDD where the media is located. However, because of this, it's not an intuitive file structure. It's located in `/data/media/library` and uses random hashes, so I can't just locate a folder and drag and drop an image.

If I have the images available locally, it would be really great to use JellyRoller to update/change photos such as `logo` or `poster` using a CLI.

**Comment by LSchallot** [comment]
I will look into adding this for the next release.

**Comment by nothing2obvi** [comment]
Sounds great! Looking forward to it.2

**Comment by LSchallot** [comment]
@nothing2obvi I have a working image update by both name and id integrated into the dev branch if you want to try it out and see if it is what you were looking for.

**Comment by nothing2obvi** [comment]
Wow, awesome. That was quick! Thank you for adding this functionality. I'll find some time to test it out this week.

**Comment by nothing2obvi** [comment]
So I build the dev branch on my Mac but I don't see it in the folder so I can't add it to PATH...

Also, what exactly are the instructions for using `update-image-by-name` and `update-image-by-id`?

**Comment by nothing2obvi** [comment]
I just tested it out. It works perfectly! Thank you! I would only suggest listing the options for imagetypes. If not in the binary itself then at least on the readme. But otherwise, this is exactly what I was looking for! I will close this feature request.
