### ISSUE TITLE
Register library

### ISSUE THREAD

**Issue by krestenlaust** [LSchallot/JellyRoller#42]
Is it possible to register a library using this tool 🤔

**Comment by LSchallot** [comment]
I assume you mean a new directory of movies or tv shows?

**Comment by krestenlaust** [comment]
Yes that's what I meant. I'm trying to create an Ansible role that sets up a standard TV shows and movies directory. But it's honestly not that important :D

**Comment by LSchallot** [comment]
I just added a new branch that adds the ability to register a library.  The "issue-42" branch has the changes if you want to build it.

If you don't see this for a few days, I may have already merged issue-42 into the 0.5.0-development branch so if the branch is gone, just try building from there.

**Comment by krestenlaust** [comment]
> I just added a new branch that adds the ability to register a library. The "issue-42" branch has the changes if you want to build it.
> 
> If you don't see this for a few days, I may have already merged issue-42 into the 0.5.0-development branch so if the branch is gone, just try building from there.

Awesome work, thanks!

**Comment by LSchallot** [comment]
Closing issue.  Will be included in the 0.5.0 release.
